packages:
  - desktop/electron
  - desktop/pet

catalog:
  '@alenaksu/json-viewer': 2.1.2
  '@biomejs/biome': 2.5.14
  '@highlightjs/cdn-assets': 11.12.0
  '@noble/hashes': 2.4.0
  '@playwright/test': 1.63.0
  '@types/jsdom': 30.0.0
  '@types/node': 24.13.6
  '@vitest/coverage-v8': 5.0.1
  '@xterm/addon-fit': 0.12.0-beta.301
  '@xterm/addon-search': 0.17.0-beta.301
  '@xterm/addon-serialize': 0.15.0-beta.301
  '@xterm/addon-unicode11': 0.10.0-beta.301
  '@xterm/addon-webgl': 0.20.0-beta.300
  '@xterm/headless': 6.1.0-beta.303
  '@xterm/xterm': 6.1.0-beta.304
  chart.js: 4.5.1
  commander: 15.0.0
  diff: 9.0.0
  diff2html: 3.4.56
  dompurify: 3.4.15
  electron: 44.4.3
  electron-builder: 26.15.3
  jsdom: 30.1.1
  marked: 18.0.13
  pdfjs-dist: 6.3.289
  plyr: 3.8.4
  sortablejs: 1.15.7
  stylelint: 17.15.0
  stylelint-config-standard: 40.0.0
  typescript: 7.0.2
  vite: 8.3.0
  viewerjs: 1.14.0
  vitest: 5.0.1
  wawoff2: 2.0.1

overrides:
  fast-uri: 3.1.6
  js-yaml: 4.3.2

allowBuilds:
  core-js: false
  esbuild: false
  electron: true
  electron-winstaller: false
minimumReleaseAgeExclude:
  - electron@44.4.3
  - html-encoding-sniffer@7.0.0
  - jsdom@30.1.1
  - w3c-xmlserializer@6.0.0
