package phic

import (
	"context"
	"errors"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/hypernewbie/phi/internal/termemu"
	"github.com/hypernewbie/phi/pkg/ws/wireproto"
)

// Opt-in wall-clock experiment: same 60Hz input, real native emulator and
// actor event loop, full View per notification. Timing is evidence, not a gate.
func TestConsolePowerProfile(t *testing.T) {
	mode := os.Getenv("PHIC_POWER_PROFILE")
	if mode == "" {
		t.Skip("set PHIC_POWER_PROFILE=interactive or watching")
	}
	m := deltaTestModel()
	m.width, m.height = 160, 45
	tab := deltaTestTab(m)
	r := m.terminalInner()
	emu, err := termemu.NewGhostty(termemu.Options{Cols: r.W, Rows: r.H, ScrollbackBytes: 64 << 20, ScrollbackLines: 10000})
	if err != nil {
		t.Skip(err)
	}
	defer emu.Close()
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	events := make(chan paneEvent, 128)
	p := &paneActor{emu: emu, ctx: ctx, events: events, inbox: make(chan paneInput, 128), outbox: make(chan paneWrite, 128)}
	p.spec.Key = tab.key
	p.noteInteraction(time.Now())
	if mode == "watching" {
		p.noteInteraction(time.Now().Add(-paneWatchingAfter))
	}
	tab.actor = p
	reads := make(chan paneRead, 128)
	done := make(chan error, 1)
	go func() { done <- p.consume(reads) }()
	duration := 10 * time.Second
	stop := time.NewTimer(duration)
	defer stop.Stop()
	feed := time.NewTicker(time.Second / 60)
	defer feed.Stop()
	data := []byte(strings.Repeat("\x1b[36mScrolling terminal output with colored text\x1b[0m\r\n", 8))
	var frontier uint64
	paints := 0
	for {
		select {
		case <-feed.C:
			reads <- paneRead{bytes: wireproto.EncodeLiveOutputFrame(frontier, data)}
			frontier += uint64(len(data))
		case <-events:
			m.View()
			paints++
		case <-stop.C:
			// FIFO barrier: drain every generated byte before reporting.
			reads <- paneRead{err: errors.New("experiment complete")}
			<-done
			got, _, _, _, _, _ := p.state()
			if got != frontier {
				t.Fatalf("admitted %d of %d bytes", got, frontier)
			}
			t.Logf("mode=%s duration=%s fed=%d admitted=%d views=%d", mode, duration, frontier, got, paints)
			return
		}
	}
}

// Benchmark the native feed/snapshot plus whole console, including scrolling.
// It deliberately does not claim to measure the host terminal's paint cost.
func BenchmarkConsoleNativeScroll(b *testing.B) {
	m := deltaTestModel()
	m.width, m.height = 160, 45
	tab := deltaTestTab(m)
	r := m.terminalInner()
	emu, err := termemu.NewGhostty(termemu.Options{Cols: r.W, Rows: r.H, ScrollbackBytes: 64 << 20, ScrollbackLines: 10000})
	if err != nil {
		b.Skip(err)
	}
	defer emu.Close()
	tab.actor = &paneActor{emu: emu}
	data := []byte(strings.Repeat("\x1b[36mScrolling terminal output with colored text\x1b[0m\r\n", 8))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if err := emu.Feed(data, termemu.SourceLive); err != nil {
			b.Fatal(err)
		}
		tab.actor.refreshFrame()
		m.View()
	}
}

// Profile the whole view, not just row formatting: panel layout and ANSI
// processing remain in the path even when the row cache hits.
func BenchmarkConsoleView(b *testing.B) {
	for _, workload := range []string{"idle", "spinner", "scroll"} {
		b.Run(workload, func(b *testing.B) {
			m := deltaTestModel()
			m.width, m.height = 160, 45
			tab := deltaTestTab(m)
			r := m.terminalInner()
			frame := deltaTestFrame(r.W, r.H)
			tab.actor = &paneActor{frame: frame, frameOK: true}
			m.View()
			b.ReportAllocs()
			b.ResetTimer()
			for i := 0; i < b.N; i++ {
				switch workload {
				case "spinner":
					frame.Cells[5][5].Text = string(rune('a' + i%26))
				case "scroll":
					for y := range frame.Cells {
						for x := range frame.Cells[y] {
							frame.Cells[y][x].Text = string(rune('a' + (x+y+i)%26))
						}
					}
				}
				tab.actor.frame = frame
				m.View()
			}
		})
	}
}
