// Copies the plain HTML/CSS assets (the step-6 rail page + the picker
// page) next to the compiled main bundle so `electron .` (dev, smoke, and
// later packaging) can load them from dist/ via loadFile, and promotes
// the CommonJS preload emitted by tsconfig.preload.json into dist/
// (the preload build keeps its own dist-preload/ outDir so its incidental
// CJS copies of the ESM modules never overwrite the ESM dist/ outputs).
//
// The main view page (web/index.html) is NOT copied here: it lives in
// web/ alongside its vendored header/styles and is generated by
// scripts/vendor-web.mjs (which runs before tsc in `pnpm run build`).
import { copyFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(here, '..', 'src');
const distDir = path.join(here, '..', 'dist');
const preloadDir = path.join(here, '..', 'dist-preload');

// renderer.js needs no copy: tsc emits it directly into dist/ (outDir:
// dist, include: src) alongside main.js/controller.js/etc., so the
// renderer.html "./renderer.js" reference resolves to the compiled module.
const assets = [
  'renderer.html',
  'rail.css',
  'rail-menu.html',
  'rail-menu.css',
  'picker.html',
];

mkdirSync(distDir, { recursive: true });
for (const name of assets) {
  copyFileSync(path.join(srcDir, name), path.join(distDir, name));
}
copyFileSync(
  path.join(preloadDir, 'preload.js'),
  path.join(distDir, 'preload.js'),
);
console.log(`copied ${assets.join(', ')}, preload.js -> dist/`);
