// @vitest-environment jsdom
/**
 * Main view page tests (vitest + jsdom). Asserts the desktop's main view
 * page — the BrowserWindow's own webContents — renders the VENDORED
 * .app-header (the same DOM as the browser Phi page's header), decorated
 * with the local caption controls, over the empty #body-area, with the
 * native drag/no-drag regions and the preload-bridge wiring.
 *
 * web/index.html and web/header.html are generated by
 * scripts/vendor-web.mjs (which runs before tsc in `pnpm run build`); the
 * tests skip with the same "run `pnpm run build` first" convention as the
 * smoke harness when the generated page is missing.
 */
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { JSDOM } from 'jsdom';
import { describe, expect, it } from 'vitest';

const here = path.dirname(fileURLToPath(import.meta.url));
const webDir = path.join(here, '..', 'web');
const rootWebIndex = path.join(here, '..', '..', '..', 'web', 'index.html');
const generatedIndex = path.join(webDir, 'index.html');
const hasGenerated = existsSync(generatedIndex);

const templateSource = readFileSync(path.join(webDir, 'index.template.html'), 'utf8');
const mainCssSource = readFileSync(path.join(webDir, 'main.css'), 'utf8');
const mainJsSource = readFileSync(path.join(webDir, 'mainview.js'), 'utf8');
const indexHtmlSource = hasGenerated ? readFileSync(generatedIndex, 'utf8') : '';
const headerHtmlSource = hasGenerated ? readFileSync(path.join(webDir, 'header.html'), 'utf8') : '';

/** The exact <header class="app-header"> block from the browser Phi page
 *  (the vendoring source of truth). */
function browserHeaderBlock(): string {
  const html = readFileSync(rootWebIndex, 'utf8');
  const start = html.indexOf('<header class="app-header"');
  const end = html.indexOf('</header>', start);
  if (start < 0 || end < 0) throw new Error('web/index.html has no app-header block');
  return html.slice(start, end + '</header>'.length);
}

describe('main view page (web/index.html)', () => {
  it('is generated from the template with the vendored header inlined', (ctx) => {
    if (!hasGenerated) {
      ctx.skip('web/index.html missing — run `pnpm run build` first');
      return;
    }
    expect(templateSource).toContain('<!--VENDORED_HEADER-->');
    expect(indexHtmlSource).toContain('<header class="app-header">');
    // The template's placeholder is replaced, never left behind.
    expect(indexHtmlSource).not.toContain('<!--VENDORED_HEADER-->');
  });

  it('parses and renders the vendored header, the caption controls and the empty body area', (ctx) => {
    if (!hasGenerated) {
      ctx.skip('web/index.html missing — run `pnpm run build` first');
      return;
    }
    // JSDOM's HTML5 parser throws on unusable input; constructing it is the
    // parse assertion.
    const doc = new JSDOM(indexHtmlSource, { url: 'file:///web/index.html' }).window.document;

    const header = doc.querySelector('.app-header');
    expect(header).not.toBeNull();
    expect(doc.querySelectorAll('.app-header').length).toBe(1);

    // The body area is the empty anchor for the host's WebContentsView children.
    const bodyArea = doc.getElementById('body-area');
    expect(bodyArea).not.toBeNull();
    expect(bodyArea?.className).toContain('desktop-body-area');

    // Exactly three caption buttons.
    const caption = doc.querySelector('.caption-controls');
    expect(caption).not.toBeNull();
    expect(doc.getElementById('caption-minimize')).not.toBeNull();
    expect(doc.getElementById('caption-maximize')).not.toBeNull();
    expect(doc.getElementById('caption-close')).not.toBeNull();
  });

  it('carries the same header DOM as the browser Phi page (single source of truth)', (ctx) => {
    if (!hasGenerated) {
      ctx.skip('web/index.html missing — run `pnpm run build` first');
      return;
    }
    // web/header.html is the raw vendored fragment; the generated page
    // embeds it verbatim except for the desktop-local caption controls
    // appended immediately before </header>. The vendored header DOM
    // is untouched — no mutations, no injected drag-gaps, no hidden
    // children. Single source of truth via vendoring.
    expect(headerHtmlSource).toBe(browserHeaderBlock());
    expect(indexHtmlSource).toContain(headerHtmlSource.slice(0, -'</header>'.length));
    // The caption-controls is the only desktop-local element injected
    // into the header — appended just before </header>.
    expect(indexHtmlSource).toContain('class="caption-controls"');
    // The real remote controls are present in the vendored header.
    expect(headerHtmlSource).toContain('id="workspace-select"');
    expect(headerHtmlSource).toContain('id="header-kanban-btn"');
    expect(headerHtmlSource).toContain('id="header-diff-toggle-btn"');
    expect(headerHtmlSource).toContain('id="hostname-display"');
    expect(headerHtmlSource).toContain('class="app-header-drag-gap"');
    // Two action buttons are icon-only by class (`Get Clipboard`,
    // `Notifications`); `header-btop-btn` has always been icon-only
    // (no `<span>` in the markup). Regression: any future addition of
    // a `<span>` to these buttons fails this test.
    expect(headerHtmlSource).toContain('id="header-clipboard-btn" class="header-btn icon-only"');
    expect(headerHtmlSource).toContain('id="header-ntfy-btn" class="header-btn icon-only"');
    expect(headerHtmlSource).not.toMatch(/id="header-clipboard-btn"[\s\S]*?<span>Get Clipboard<\/span>/);
    expect(headerHtmlSource).not.toMatch(/id="header-ntfy-btn"[\s\S]*?<span>Notifications<\/span>/);
  });
});

describe('main view page chrome (web/main.css)', () => {
  it('does not override any vendored .app-header styling (TBAR is byte-identical to web/index.html)', () => {
    // The TBAR pipeline rule: the desktop TBAR is the EXACT same DOM
    // and styling as the browser Phi's `.app-header`.
    // main.css is only allowed to:
    //   - add `-webkit-app-region` rules (frameless-window drag regions,
    //     additive to the vendor's properties);
    //   - style desktop-local elements (`.caption-controls`,
    //     `.desktop-body-area`, `.desktop-auth-modal`,
    //     `.app-header-drag-gap` flex sizing);
    //   - suppress the file://-specific `.access-auth-overlay` (scoped
    //     to `html[data-phi-desktop-root]`).
    // Any rule that overrides how `.app-header` RENDERS (background,
    // backdrop-filter, justify-content, height, brand-name, activity
    // indicator) is a sidecar and is forbidden.
    // The desktop is allowed exactly ONE rule block that targets
    // `.app-header` directly (the additive drag region), and ONE
    // comma-separated selector list for the no-drag children — both
    // are frameless-window requirements, not visual overrides.
    const directAppHeaderRule = mainCssSource.match(/\n\.app-header\s*\{([^}]*)\}/);
    expect(directAppHeaderRule).not.toBeNull();
    expect(directAppHeaderRule![1]).toContain('-webkit-app-region: drag');
    expect(directAppHeaderRule![1]).not.toMatch(/background|backdrop|justify-content|height/);
    // Negative assertions: no desktop-side override of brand-name,
    // activity-indicator, or any vendor styling property.
    expect(mainCssSource).not.toMatch(/\.brand-name\s*\{[^}]*display:\s*none/);
    expect(mainCssSource).not.toMatch(/#terminal-activity-indicator\s*\{[^}]*display:\s*none/);
    expect(mainCssSource).not.toMatch(/\.app-header\s*\{[^}]*background/);
    expect(mainCssSource).not.toMatch(/\.app-header\s*\{[^}]*backdrop/);
    expect(mainCssSource).not.toMatch(/\.app-header\s*\{[^}]*justify-content/);
    expect(mainCssSource).not.toMatch(/\.app-header\s*\{[^}]*height:/);
    expect(mainCssSource).not.toMatch(/\.header-actions\s*\{/);
    expect(templateSource).toMatch(/<html[^>]*data-phi-desktop-root/);
  });

  it('uses the desktop-root marker (not data-phi-desktop) so the vendor’s body beheading does not apply', () => {
    // The vendored stylesheet has `html[data-phi-desktop] .app-header
    // { display: none }` — that rule is meant for the BODY when
    // ?desktop=1 is loaded. The desktop main view uses
    // `data-phi-desktop-root` instead so the vendor's beheading does
    // not apply, and the header renders by default.
    expect(templateSource).toMatch(/<html[^>]*data-phi-desktop-root/);
    expect(templateSource).not.toMatch(/<html[^>]*data-phi-desktop(?!\w|-root)/);
    expect(mainCssSource).not.toMatch(/html\[data-phi-desktop\][^{]*\.app-header/);
  });

  it('does not mutate the vendored header — the vendor script only appends caption controls', () => {
    // The TBAR pipeline rule: the vendored header DOM is byte-identical
    // to the browser Phi's `.app-header`. The only desktop-local element
    // injected by the vendor script is `.caption-controls`, appended
    // just before </header>. No drag-gap injections, no structural
    // mutations — any change to how the header renders belongs in
    // web/index.html first and gets re-vendored (single source of
    // truth via vendoring).
    const vendorSource = readFileSync(
      path.join(here, '..', 'scripts', 'vendor-web.mjs'),
      'utf8',
    );
    expect(vendorSource).toContain('CAPTION_CONTROLS');
    expect(vendorSource).toContain('caption-controls');
    expect(vendorSource).not.toMatch(/DESKTOP_DRAG_GAPS|preWorkspace|postWorkspace/);
    expect(vendorSource).not.toMatch(/inject.*drag-gap|inject.*workspace/);
  });

  it('marks interactive header children and the caption controls no-drag', () => {
    expect(mainCssSource).toMatch(/\.app-header\s+button[^{]*\{[\s\S]*?-webkit-app-region: no-drag/);
    expect(mainCssSource).toMatch(/\.app-header\s+select[^{]*\{[\s\S]*?-webkit-app-region: no-drag/);
    expect(mainCssSource).toMatch(/\.caption-controls\s*\{[\s\S]*?-webkit-app-region: no-drag/);
  });

  it('pushes the caption controls to the right edge of the header content area', () => {
    // The caption lane is positioned absolutely at the right edge of
    // the `.app-header` (which is `position: relative` from the
    // vendor) so the X button lands at window_right, not 16px inside
    // it. The vendor's `.app-header` has `padding: 0 16px` for the
    // browser Phi page's brand gutters; absolute positioning on the
    // desktop-only caption lane makes the X flush regardless of that
    // padding. The lane is removed from the flex flow so the action
    // cluster's natural width isn't pushed inward.
    const captionBlock = mainCssSource.match(/\.caption-controls\s*\{([^}]*)\}/);
    expect(captionBlock).not.toBeNull();
    expect(captionBlock![1]).toContain('position: absolute');
    expect(captionBlock![1]).toContain('right: 0');
    expect(captionBlock![1]).toContain('top: 0');
    expect(captionBlock![1]).toContain('height: 100%');
    expect(captionBlock![1]).toContain('flex: 0 0 138px');
    // No padded lane reserves a gap beside the window edge.
    expect(mainCssSource).not.toContain('154px');
  });

  it('keeps the middle gap draggable and the body area input-transparent', () => {
    expect(mainCssSource).toMatch(/\.app-header-drag-gap\s*\{[\s\S]*?-webkit-app-region: drag/);
    expect(mainCssSource).toMatch(/\.desktop-body-area\s*\{[\s\S]*?pointer-events: none/);
    expect(mainCssSource).toMatch(/\.desktop-body-area\s*\{[\s\S]*?top: var\(--header-height\)/);
  });

  it('suppresses the browser’s access-auth-overlay on the desktop-root page only', () => {
    expect(mainCssSource).toMatch(/html\[data-phi-desktop-root\][^{]*\.access-auth-overlay\s*\{[^}]*display:\s*none\s*!important/);
  });
});

describe('main view page behaviors (web/mainview.js)', () => {
  it('runs the browser header code: imports the vendored modules instead of reimplementing them', () => {
    // The TBAR must run the same code the browser Phi page runs: the
    // canonical helpers are imported from the vendored web/ sources, not
    // reimplemented with hand-rolled "parity" copies.
    expect(mainJsSource).toContain("import { ACCENT_COLORS, App } from './vendor/app.js'");
    expect(mainJsSource).toContain("import { displayHostname, formatWorkspaceLabel } from './vendor/util.js'");
    expect(mainJsSource).toContain("import { SessionsManager } from './vendor/sessions.js'");
    // The canonical application paths are called through the vendored
    // classes (applyAccentTheme, updateWorkspaceSelectWidth) rather than
    // reimplemented locally.
    expect(mainJsSource).toContain('App.prototype.applyAccentTheme.call');
    expect(mainJsSource).toContain('SessionsManager.prototype.updateWorkspaceSelectWidth.call');
    // No hand-rolled accent palette may exist in the local wiring.
    expect(mainJsSource).not.toMatch(/#[0-9a-f]{6}/i);
  });

  it('drives the window controls and window state through the preload bridge', () => {
    expect(mainJsSource).toContain('postWindowMinimize()');
    expect(mainJsSource).toContain('postWindowToggleMaximize()');
    expect(mainJsSource).toContain('postWindowClose()');
    expect(mainJsSource).toContain('onWindowState(');
    expect(mainJsSource).toContain('onWindowTitle(');
  });

  it('populates the header from the active server config and relays actions to the body', () => {
    expect(mainJsSource).toContain('fetchServerConfig()');
    expect(mainJsSource).toContain('fetchActiveWorkspace');
    expect(mainJsSource).toContain('postHeaderAction(');
    expect(mainJsSource).toContain('onActiveServer(');
    expect(mainJsSource).toContain('getElementById(\'workspace-select\')');
  });

  it('relays every action-cluster button and the workspace change to the body', () => {
    for (const id of [
      'header-clipboard-btn',
      'header-ntfy-btn',
      'header-btop-btn',
      'header-kanban-btn',
      'header-diff-toggle-btn',
      'header-config-pill',
      'add-workspace-btn',
      'remove-workspace-btn',
    ]) {
      expect(mainJsSource).toContain(id);
    }
    expect(mainJsSource).toContain("{ kind: 'workspace', value: workspaceSelect.value }");
  });
});

describe('vendored browser JS (web/vendor/*)', () => {
  it('copies the browser header behavior modules byte-identical (single source of truth)', (ctx) => {
    const vendorDir = path.join(webDir, 'vendor');
    if (!existsSync(vendorDir)) {
      ctx.skip('web/vendor missing — run `pnpm run build` first');
      return;
    }
    for (const name of ['app.js', 'sessions.js', 'util.js']) {
      const vendored = readFileSync(path.join(vendorDir, name), 'utf8');
      const canonical = readFileSync(path.join(rootWebIndex, '..', name), 'utf8');
      expect(vendored).toBe(canonical);
    }
  });

  it('ships every ACCENT_COLORS theme (22) in the vendored app.js', (ctx) => {
    const vendored = path.join(webDir, 'vendor', 'app.js');
    if (!existsSync(vendored)) {
      ctx.skip('web/vendor missing — run `pnpm run build` first');
      return;
    }
    const keys = [...readFileSync(vendored, 'utf8').matchAll(/^\s{4}([a-z]+):\s*\{\s*accent: '/gm)].map(
      (m) => m[1],
    );
    expect(keys.length).toBe(22);
    for (const k of [
      'purple', 'blue', 'green', 'amber', 'red', 'pink', 'teal', 'indigo',
      'orange', 'cyan', 'rose', 'lime', 'white', 'gold', 'violet', 'emerald',
      'neon', 'coral', 'fuchsia', 'canary', 'copper', 'mint',
    ]) {
      expect(keys).toContain(k);
    }
  });

  it('imports the vendored app.js module graph and exposes the full palette', async (ctx) => {
    const vendored = path.join(webDir, 'vendor', 'app.js');
    if (!existsSync(vendored)) {
      ctx.skip('web/vendor missing — run `pnpm run build` first');
      return;
    }
    // The module graph (terminal/ws/sessions/util/...) must load without
    // booting the app: importing app.js only defines classes and the
    // palette (no App instantiation at module scope).
    const mod = await import(pathToFileURL(vendored).href);
    expect(Object.keys(mod.ACCENT_COLORS).length).toBe(22);
  });

  it('loads the vendored module entry in the main view page (no sidecar script)', () => {
    expect(templateSource).toContain('<script type="module" src="./mainview.js"></script>');
    expect(templateSource).not.toContain('src="./main.js"');
  });
});
