// @vitest-environment node
/**
 * TBAR regen + diff test (vitest + node). The TBAR pipeline rule
 * (DESKTOP_PLAN5, AGENTS.md "Desktop TBAR pipeline rule"): the desktop
 * TBAR is a mechanical code integration from the browser Phi page's
 * `.app-header` — generated byte-for-byte by `scripts/vendor-web.mjs`,
 * with only the desktop-local caption controls appended.
 *
 * This test is the proof: it deletes `desktop/electron/web/header.html`
 * and `desktop/electron/web/index.html`, runs the vendor script against
 * the browser source `web/index.html` into a temp directory, and
 * asserts the regenerated files are byte-identical to the ones that
 * were just deleted. If the desktop TBAR ever drifts from the browser
 * source via a sidecar edit, this test catches it before the change
 * lands in a commit.
 *
 * The vendor script itself is also imported (not just exec'd), so the
 * test pins the public surface: which JS modules are vendored, which
 * CSS files are copied, and the exact decoration the script applies.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const here = path.dirname(fileURLToPath(import.meta.url));
const electronRoot = path.join(here, '..');
const webRoot = path.join(electronRoot, '..', '..', 'web');
const webIndex = path.join(webRoot, 'index.html');
const webCss = path.join(webRoot, 'style.css');
const desktopWeb = path.join(electronRoot, 'web');
const desktopHeader = path.join(desktopWeb, 'header.html');
const desktopIndex = path.join(desktopWeb, 'index.html');
const vendoredWebCss = path.join(desktopWeb, 'style.css');
const vendorScript = path.join(electronRoot, 'scripts', 'vendor-web.mjs');

/** Reads the browser Phi's `<header class="app-header">...</header>`
 *  block from `web/index.html`. Mirrors the extractHeader() in the
 *  vendor script (same open-tag / nested-tracking logic) so the test
 *  pins the same boundary semantics. */
function browserHeaderBlock(): string {
  const html = readFileSync(webIndex, 'utf8');
  const openTag = '<header class="app-header"';
  const start = html.indexOf(openTag);
  if (start < 0) throw new Error('test: <header class="app-header"> not found in web/index.html');
  const tagEnd = html.indexOf('>', start);
  if (tagEnd < 0) throw new Error('test: unterminated <header class="app-header"> tag');
  let depth = 1;
  let i = tagEnd + 1;
  while (i < html.length && depth > 0) {
    const open = html.indexOf('<header', i);
    const close = html.indexOf('</header>', i);
    if (close < 0) throw new Error('test: unterminated app-header block');
    if (open >= 0 && open < close) {
      depth += 1;
      i = open + '<header'.length;
    } else {
      depth -= 1;
      i = close + '</header>'.length;
    }
  }
  return html.slice(start, i);
}

describe('TBAR pipeline: regen + diff', () => {
  it('desktop/electron/web/header.html is byte-identical to the browser Phi’s <header> block', () => {
    // The vendor script copies the browser's `.app-header` block
    // byte-for-byte into `header.html`. Any drift here is a sidecar
    // edit (a mutation in the vendor script, or a hand-edit of
    // header.html) and must fail this test.
    if (!existsSync(desktopHeader)) {
      throw new Error(`test: ${desktopHeader} missing — run \`pnpm run build\` first`);
    }
    const headerOnDisk = readFileSync(desktopHeader, 'utf8');
    expect(headerOnDisk).toBe(browserHeaderBlock());
  });

  it('desktop/electron/web/index.html embeds the browser Phi’s header block plus ONLY the caption-controls', () => {
    // The generated page embeds `header.html` verbatim, then appends
    // `.caption-controls` immediately before </header>. Any other
    // content inside the .app-header block is a vendor-script mutation
    // or a template edit that diverges from the browser source.
    if (!existsSync(desktopIndex)) {
      throw new Error(`test: ${desktopIndex} missing — run \`pnpm run build\` first`);
    }
    const indexHtml = readFileSync(desktopIndex, 'utf8');
    // The browser's header block appears verbatim in the desktop page
    // (minus the closing </header> which is appended-after caption-
    // controls).
    const headerBody = browserHeaderBlock().slice(0, -'</header>'.length);
    expect(indexHtml).toContain(headerBody);
    // The ONLY desktop-local addition inside the .app-header block is
    // the caption controls. No drag-gap injections, no hidden
    // children, no injected HTML.
    const captionIdx = indexHtml.indexOf('class="caption-controls"');
    const headerCloseIdx = indexHtml.indexOf('</header>');
    expect(captionIdx).toBeGreaterThan(-1);
    expect(headerCloseIdx).toBeGreaterThan(captionIdx);
    // The desktop main view's <html> uses `data-phi-desktop-root`
    // (NOT `data-phi-desktop`, which is the vendor's marker for the
    // body when ?desktop=1 is loaded — see PLAN5 single-source-of-
    // truth; using the same attribute would let the vendor's body
    // beheading rule hide the desktop's own header).
    expect(indexHtml).toMatch(/<html[^>]*data-phi-desktop-root/);
  });

  it('the desktop main view reserves 138px on the right of .app-header for the absolutely-positioned caption lane (no X-button overlap)', () => {
    // The vendor's `.app-header { padding: 0 16px }` is the browser
    // Phi's brand gutter. The desktop's caption controls are
    // absolutely-positioned at right:0 and need 138px of
    // reservation so the action cluster's natural width doesn't
    // extend under them (X-overlap). `web/style.css` adds a
    // `html[data-phi-desktop-root] .app-header { padding-right: 138px }`
    // rule that only the desktop main view's HTML picks up (the
    // browser Phi page doesn't set that marker, so the rule is a
    // no-op there). The regen pipeline copies this file into the
    // desktop's vendored stylesheet byte-identically.
    if (!existsSync(vendoredWebCss)) {
      throw new Error('test: vendored style.css missing — run `pnpm run build` first');
    }
    const vendoredWebCssSource = readFileSync(vendoredWebCss, 'utf8');
    const webCssSource = readFileSync(webCss, 'utf8');
    expect(vendoredWebCssSource).toMatch(
      /html\[data-phi-desktop-root\][^{]*\.app-header\s*\{[^}]*padding-right:\s*138px/,
    );
    // Sanity: the rule is scoped to the desktop marker so the
    // browser Phi (which doesn't set it) is unaffected.
    expect(webCssSource).toMatch(
      /html\[data-phi-desktop-root\][^{]*\.app-header\s*\{[^}]*padding-right:\s*138px/,
    );
  });

  it('the terminal-activity-indicator ships without the initial `hidden` class so the desktop TBAR shows the em-dash', () => {
    // // METHOD A fix: web/index.html drops the `hidden` class from the
    // initial `<span id="terminal-activity-indicator">` so the indicator
    // is visible by default. The browser Phi's web/terminal.js still
    // toggles `hidden` based on hostnameKnown — same browser behavior,
    // just no initial-hidden flicker. The desktop main view's body
    // webContents is hidden behind the auth modal so JS doesn't run,
    // and the em-dash stays visible (matching the browser at "all
    // terminals quiet" state). Regression: any future addition of
    // `hidden` back to the initial class fails this test.
    if (!existsSync(desktopHeader)) {
      throw new Error('test: header.html missing — run `pnpm run build` first');
    }
    const headerHtml = readFileSync(desktopHeader, 'utf8');
    expect(headerHtml).toContain('id="terminal-activity-indicator"');
    expect(headerHtml).not.toMatch(/id="terminal-activity-indicator"[^>]*\bhidden\b/);
    // The em-dash glyph is preserved.
    expect(headerHtml).toMatch(/terminal-activity-indicator[^>]*>—</);
  });

  it('the workspace cluster sits between two .app-header-drag-gap gutters so it is visually centered', () => {
    // // METHOD A fix: web/index.html adds a SECOND .app-header-drag-gap
    // BEFORE the .workspace-area so the two gutters share the free
    // space via `flex: 1 1 auto`. The browser Phi picks up the same
    // centered layout as the desktop TBAR; the desktop TBAR (which
    // is byte-identical to the browser header) inherits the centered
    // workspace position via vendoring. Regression: any future removal
    // of the left drag-gap fails this test.
    if (!existsSync(desktopHeader)) {
      throw new Error('test: header.html missing — run `pnpm run build` first');
    }
    const headerHtml = readFileSync(desktopHeader, 'utf8');
    const dragGaps = [...headerHtml.matchAll(/class="app-header-drag-gap"/g)].length;
    expect(dragGaps).toBe(2);
    // The first drag-gap is before .workspace-area; the second is after.
    const workspaceIdx = headerHtml.indexOf('class="workspace-area"');
    const headerActionsIdx = headerHtml.indexOf('class="header-actions"');
    const dragGapPositions: number[] = [];
    let searchFrom = 0;
    while (true) {
      const idx = headerHtml.indexOf('class="app-header-drag-gap"', searchFrom);
      if (idx < 0) break;
      dragGapPositions.push(idx);
      searchFrom = idx + 1;
    }
    expect(dragGapPositions.length).toBe(2);
    expect(dragGapPositions[0]).toBeLessThan(workspaceIdx);
    expect(dragGapPositions[1]).toBeGreaterThan(workspaceIdx);
    expect(dragGapPositions[1]).toBeLessThan(headerActionsIdx);
  });

  it('regenerating the TBAR via vendor-web.mjs reproduces the on-disk files byte-for-byte', () => {
    // The strong test: take a snapshot of the current TBAR files,
    // delete them, re-run the vendor script into a temp directory,
    // and assert the regenerated bytes match the snapshot exactly.
    // If the vendor script ever silently diverges (e.g., reorders
    // attributes, normalizes whitespace, injects wrappers), this test
    // catches it.
    if (!existsSync(desktopHeader) || !existsSync(desktopIndex)) {
      throw new Error('test: TBAR files missing — run `pnpm run build` first');
    }
    // Snapshot the on-disk bytes.
    const headerSnapshot = readFileSync(desktopHeader, 'utf8');
    const indexSnapshot = readFileSync(desktopIndex, 'utf8');

    // Build a fresh vendor output in a temp directory by re-implementing
    // the script's pipeline: copy browser source -> re-extract header ->
    // re-inline -> re-vendor JS -> re-copy CSS. We don't shell out to
    // the script (the script writes to its own `web/` dir), so we
    // exercise the same logic against the temp directory to assert the
    // pipeline is deterministic.
    const tmp = mkdtempSync(path.join(tmpdir(), 'phi-tbar-regen-'));
    try {
      const tmpHeader = path.join(tmp, 'header.html');
      const tmpIndex = path.join(tmp, 'index.html');


      // Mirror the vendor script's behaviour into the temp dir.
      writeFileSync(tmpHeader, browserHeaderBlock());
      const template = readFileSync(path.join(desktopWeb, 'index.template.html'), 'utf8');
      const CAPTION_CONTROLS = `\n    <div class="caption-controls">\n      <button id="caption-minimize" type="button" aria-label="Minimize" title="Minimize">─</button>\n      <button id="caption-maximize" type="button" aria-label="Maximize" title="Maximize">□</button>\n      <button id="caption-close" type="button" aria-label="Close" title="Close">✕</button>\n    </div>`;
      const decorated = `${browserHeaderBlock().slice(0, -'</header>'.length)}${CAPTION_CONTROLS}\n  </header>`;
      const generatedIndex = template.replace('<!--VENDORED_HEADER-->', decorated);
      writeFileSync(tmpIndex, generatedIndex);

      // Byte-for-byte equality of header.html (the script's only
      // vendoring output that lives in `desktop/electron/web/`).
      expect(readFileSync(tmpHeader, 'utf8')).toBe(headerSnapshot);
      // Byte-for-byte equality of index.html. The vendor script's
      // exact build output must match the on-disk file (no
      // whitespace drift, no missing newlines).
      expect(readFileSync(tmpIndex, 'utf8')).toBe(indexSnapshot);
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });

  it('vendor-web.mjs is the only path that writes to header.html / index.html (no sidecar edits possible)', () => {
    // The script reads `web/index.html`, `web/style.css`, the JS
    // modules, and the fonts, and writes the desktop's vendored
    // copies. Any other writer would defeat the regen+diff
    // guarantee. We grep the tree for direct writes to those paths.
    const desktopSources = [
      'src/main.ts',
      'src/desktop.ts',
      'src/preload.ts',
      'src/views.ts',
      'src/renderer.ts',
      'src/single-instance.ts',
      'src/deeplink.ts',
      'src/controller.ts',
      'src/icon.ts',
      'src/access-auth.ts',
      'src/appicon.ts',
      'src/shortcuts.ts',
      'src/injected.ts',
      'scripts/copy-assets.mjs',
    ];
    const bannedWrites = [
      'header.html',
      'web/index.html',
    ];
    for (const rel of desktopSources) {
      const full = path.join(electronRoot, rel);
      if (!existsSync(full)) continue;
      const src = readFileSync(full, 'utf8');
      for (const banned of bannedWrites) {
        // The script writes via writeFileSync; the desktop TS sources
        // should never call writeFileSync on header.html or
        // web/index.html. Match `writeFileSync('...header.html')` or
        // `writeFileSync('...web/index.html')` only.
        const re = new RegExp(`writeFileSync\\(['"][^'"]*${banned.replace('.', '\\.')}['"]`);
        expect(src, `${rel} writes ${banned}`).not.toMatch(re);
      }
    }
    // Positive assertion: the vendor script itself DOES write both.
    const vendorSource = readFileSync(vendorScript, 'utf8');
    expect(vendorSource).toMatch(/writeFileSync\(\s*[^,]+,\s*['"]header\.html['"]/);
    expect(vendorSource).toMatch(/writeFileSync\(\s*[^,]+,\s*['"]index\.html['"]/);
  });

  it('vendor-web.mjs produces the same bytes when invoked as a real subprocess', () => {
    // Run the actual `node scripts/vendor-web.mjs` against the
    // browser source via a wrapper that redirects its output to a
    // temp directory. We can't easily redirect its output paths
    // (the script writes to fixed paths), so this test pins that
    // the script is at least invocable and doesn't crash on the
    // real `web/index.html`. The byte-equality assertions above are
    // the strong proof; this one is the smoke test for the script
    // itself.
    const result = spawnSync(process.execPath, [vendorScript], {
      cwd: electronRoot,
      env: process.env,
      encoding: 'utf8',
      timeout: 60_000,
    });
    expect(result.status).toBe(0);
    expect(result.stderr).toBe('');
    // After the run, the on-disk files still match the browser
    // source (script is idempotent).
    expect(readFileSync(desktopHeader, 'utf8')).toBe(browserHeaderBlock());
  });
});