/**
 * System tray for the Electron main process — parity with the Wails
 * `desktop/internal/tray` package, implemented with the public Electron
 * `Tray` + `Menu` + `nativeImage` API only (no native Win32 calls, no
 * NSStatusItem / StatusNotifierItem code paths — those are wrapped by
 * Electron's portability).
 *
 * Menu contract (right-click; left-click too on macOS, the platform
 * convention):
 *   - `Show Phi` -> posts `{ kind: 'show' }` on the tray channel; the
 *     host loop (src/main.ts) brings the main window to the foreground
 *     (restore()+focus()).
 *   - `Profiles > {id} {name}` (one entry per saved profile) -> posts
 *     `{ kind: 'select-profile', id }` on the tray channel. Step 5's
 *     controller integration is the receiver; this slice only emits the
 *     intent.
 *   - `Close to tray` / `Sync board alerts` checkboxes -> post
 *     `toggle-close-to-tray` / `toggle-sync-alerts`; the host-loop
 *     receiver flips the persisted preference.
 *   - `Quit` -> posts `{ kind: 'quit' }` on the tray channel; the
 *     host-loop receiver (src/main.ts) logs, notifies the main window
 *     and calls `app.quit()` (the tray no longer quits directly — the
 *     receiver owns the quit since step 5).
 *
 * Tooltip contract: `Phi — <name> (<host:port>)` for the active profile
 * (origin formatted as host:port), with ` (N unread)` appended when the
 * active profile has unread > 0. `setActiveProfile(p)` and
 * `setUnread(id, n)` drive it; `setUnread` changes the visible tooltip
 * only when id is the active profile (per-profile counts are stored
 * regardless, so the suffix is correct when that profile becomes active).
 *
 * Testability: pure dependency injection via TrayDeps — the tray imports
 * no controller; the host loop in src/main.ts is the bridge. The
 * 'electron' module is only touched inside setupTray (never at module
 * load), so tests stub it with recording fakes (see test/tray.test.ts)
 * and no real Tray/Menu/nativeImage/app is ever constructed. The icon
 * asset is resolved at production load time against the package assets/
 * directory; when it is missing (or the injected nativeImage reports an
 * empty image) the tray logs once and continues with Electron's default
 * empty icon — the same convention the Wails tray uses for missing icon
 * resources.
 */
import { Menu, nativeImage, Tray } from 'electron';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));

/**
 * The tray icon asset, resolved at production load time:
 * `<dist>/../assets/tray.ico` = `desktop/electron/assets/tray.ico` (the
 * multi-size icon generated by scripts/gen-icon.mjs). Windows loads the
 * ICO directly; other platforms fall back to the sibling tray.png.
 * main.ts passes it explicitly through TrayDeps.iconPath (the production
 * override); tests inject a fake nativeImage so the missing-asset path is
 * exercised without touching disk.
 */
export const TRAY_ICON_PATH = path.join(here, '..', 'assets', 'tray.ico');

/** The typed IPC channel the tray menu intents are posted on. */
export const TRAY_COMMAND_CHANNEL = 'phi:tray-command';

/** One tray menu intent (posted on TRAY_COMMAND_CHANNEL). */
export type TrayCommand =
  | { kind: 'show' }
  | { kind: 'select-profile'; id: string }
  | { kind: 'toggle-close-to-tray' }
  | { kind: 'toggle-sync-alerts' }
  | { kind: 'quit' };

/** One saved profile (the rail model's tray-relevant slice). */
export interface TrayProfile {
  /** The profile id (routing identity). */
  id: string;
  /** The display name (menu label + tooltip). */
  name: string;
  /** The origin URL (tooltip). */
  origin: string;
  /** Connection health, when known (menu label status; unknown when absent). */
  health?: 'up' | 'down' | 'unknown';
  /** Unread message count, when known (menu label suffix; 0 when absent). */
  unread?: number;
}

/**
 * The tray's dependency surface (pure DI — no controller import). The
 * production host loop (src/main.ts) wires these to the step-5 controller
 * or to noops until it lands; tests inject recording fakes.
 */
export interface TrayDeps {
  /** The saved profiles, in rail order (menu submenu + tooltip data). */
  getProfiles(): TrayProfile[];
  /** The active profile id ('' when none). */
  getActiveProfileId(): string;
  /** The stored unread count for a profile. */
  getUnread(id: string): number;
  /** The persisted close-to-tray preference (the menu checkbox state). */
  getCloseToTray(): boolean;
  /** The persisted sync-board desktop-alert preference (the menu checkbox state). */
  getSyncAlerts(): boolean;
  /** Posts a TrayCommand on a channel (the host loop bridges intents). */
  ipcSend(channel: string, payload: unknown): void;
  /** Failure/one-time logger (production: console; tests record it). */
  log(msg: string): void;
  /** Production icon path (defaults to TRAY_ICON_PATH). */
  iconPath?: string;
}

/** The tray surface the host loop drives. */
export interface TrayHandle {
  /**
   * Marks p as the active profile and refreshes the tooltip with its
   * name, origin and (stored) unread suffix.
   */
  setActiveProfile(p: TrayProfile): void;
  /**
   * Stores profileId's unread count (clamped at 0). The visible tooltip
   * changes only when profileId is the active profile (which then gets
   * the " (N unread)" suffix).
   */
  setUnread(profileId: string, n: number): void;
  /**
   * Rebuilds the context menu from the current profile list (fresh
   * Menu.buildFromTemplate over the same retained handlers). The tray
   * itself is NOT recreated — only the popup menu is refreshed.
   */
  rebuildMenu(): void;
  /** Removes the tray icon (before-quit / window-all-closed teardown). */
  close(): void;
}

/** One entry of the tray context menu (pure, structural). */
export interface TrayMenuEntry {
  label: string;
  /** Leaf action (omitted on the Profiles submenu parent). */
  click?: () => void;
  submenu?: TrayMenuEntry[];
  /** Checkbox item (the Close to tray toggle). */
  type?: 'checkbox';
  /** The checkbox state — only meaningful when type === 'checkbox'. */
  checked?: boolean;
}
/** The menu action handlers the pure menu builder calls. */
export interface TrayMenuHandlers {
  show: () => void;
  selectProfile: (id: string) => void;
  toggleCloseToTray: () => void;
  toggleSyncAlerts: () => void;
  quit: () => void;
}

/**
 * The minimal tray surface the menu-event wiring needs (the real Electron
 * Tray satisfies it).
 */
export interface TrayLike {
  on(event: string, listener: () => void): unknown;
  popUpContextMenu(menu?: unknown): void;
}

/**
 * The canonical display hostname of an origin: the URL hostname, minus
 * any `.local` suffix, uppercased — never the port (e.g.
 * `http://charon.local:7070/` -> `CHARON`). Falls back to the raw
 * origin when it is not parseable, '' when empty.
 */
export function formatCanonicalHostname(origin: string): string {
  if (!origin) return '';
  try {
    return new URL(origin).hostname.replace(/\.local\.?$/i, '').toUpperCase() || origin;
  } catch {
    return origin;
  }
}

/**
 * The display label for a profile name: host[:port] names (the default
 * for unnamed profiles) render as the canonical hostname (`CHARON`, not
 * `charon.local:7070`); explicit names pass through unchanged.
 */
function canonicalHostnameLabel(name: string): string {
  const trimmed = name.trim();
  if (!trimmed) return name;
  const looksLikeHostPort = /^[^:]+:\d+$/.test(trimmed);
  const looksLikeLocalHost = /^[^:]+\.local(:\d+)?$/i.test(trimmed);
  if (looksLikeHostPort || looksLikeLocalHost) {
    const canonical = formatCanonicalHostname(`http://${trimmed}`);
    if (canonical !== trimmed) return canonical;
  }
  return name;
}

/**
 * Renders the one-line tray tooltip: `Phi — <name>` with the canonical
 * hostname as ` (<hostname>)` and the unread suffix ` (N unread)` when
 * N > 0. When the name is empty the canonical hostname stands in for it,
 * so a name-less active profile still reads `Phi — CHARON (2 unread)`.
 */
export function buildTooltip(opts: { name?: string; origin?: string; unread?: number }): string {
  const originText = opts.origin ? formatCanonicalHostname(opts.origin) : '';
  const display = opts.name && opts.name.trim() !== '' ? canonicalHostnameLabel(opts.name) : originText;
  let tip = display ? `Phi — ${display}` : 'Phi';
  if (originText && originText !== display) tip += ` (${originText})`;
  if (opts.unread !== undefined && opts.unread > 0) tip += ` (${opts.unread} unread)`;
  return tip;
}

/**
 * Renders a profile label for health display: `name — up` when the
 * profile is healthy, `name — down` when it is unhealthy, and the bare
 * name when health is unknown. Host[:port] names are canonicalized first
 * (the canonical hostname, never the port). Appends ` (N)` when
 * N unread > 0.
 */
export function formatProfileLabel(name: string, health: 'up' | 'down' | 'unknown', unread: number): string {
  const display = canonicalHostnameLabel(name);
  const status = health === 'up' ? `${display} — up` : health === 'down' ? `${display} — down` : display;
  return unread > 0 ? `${status} (${unread})` : status;
}

/**
 * Builds the tray context menu (pure, testable): Show Phi, Profiles >
 * {id} {name} (one entry per saved profile), the Close to tray and Sync
 * board alerts checkboxes (checked state from closeToTray/syncAlerts)
 * and Quit. The Profiles submenu is omitted when there are no saved
 * profiles (Wails parity). The menu is a snapshot of the profile list
 * and the preferences at build time; the host loop calls
 * TrayHandle.rebuildMenu() (src/tray.ts) to refresh it when either
 * changes.
 */
export function buildTrayMenu(
  profiles: TrayProfile[],
  handlers: TrayMenuHandlers,
  closeToTray: boolean,
  syncAlerts: boolean,
): TrayMenuEntry[] {
  const entries: TrayMenuEntry[] = [{ label: 'Show Phi', click: handlers.show }];
  if (profiles.length > 0) {
    entries.push({
      label: 'Profiles',
      submenu: profiles.map((p) => ({
        label: formatProfileLabel(p.name, p.health ?? 'unknown', p.unread ?? 0),
        click: () => handlers.selectProfile(p.id),
      })),
    });
  }
  entries.push({
    label: 'Close to tray',
    type: 'checkbox',
    checked: closeToTray,
    click: handlers.toggleCloseToTray,
  });
  entries.push({
    label: 'Sync board alerts',
    type: 'checkbox',
    checked: syncAlerts,
    click: handlers.toggleSyncAlerts,
  });
  entries.push({ label: 'Quit', click: handlers.quit });
  return entries;
}

/**
 * Wires the tray's menu events: right-click pops the context menu on
 * every platform; on macOS the menu also pops on left-click (the platform
 * convention). popUpContextMenu is used (not setContextMenu) so the
 * wiring is explicit, the menu pops at the cursor, and macOS never shows
 * a double menu. The menu is fetched through the getMenu() getter at
 * popup time, so a rebuildMenu() swap is picked up by the next popup
 * (the events are wired once, against the mutable current menu).
 */
export function wireTrayEvents(tray: TrayLike, getMenu: () => Menu, platform: NodeJS.Platform): void {
  tray.on('right-click', () => tray.popUpContextMenu(getMenu()));
  if (platform === 'darwin') {
    tray.on('click', () => tray.popUpContextMenu(getMenu()));
  }
}

/**
 * Creates the system tray and returns its handle. The icon comes from
 * deps.iconPath (default TRAY_ICON_PATH); a missing/empty image is logged
 * once and the tray continues with Electron's default empty icon (the
 * Wails missing-icon convention).
 */
export function setupTray(deps: TrayDeps): TrayHandle {
  const iconPath = deps.iconPath ?? TRAY_ICON_PATH;
  let icon = nativeImage.createFromPath(iconPath);
  if (icon.isEmpty() && iconPath.endsWith('.ico')) {
    // Windows ICO only: other platforms fall back to the sibling PNG.
    icon = nativeImage.createFromPath(iconPath.replace(/\.ico$/, '.png'));
  }
  if (!icon.isEmpty()) {
    if (process.platform === 'darwin') {
      if (typeof icon.resize === 'function') {
        icon = icon.resize({ width: 16, height: 16 });
      }
      if (typeof icon.setTemplateImage === 'function') {
        icon.setTemplateImage(true);
      }
    }
  } else {
    deps.log(`phi-desktop: tray icon missing at ${iconPath}; continuing with the default empty icon`);
  }
  const tray = new Tray(icon);
  tray.setToolTip('Phi');

  const state: { active: TrayProfile | null; unread: Map<string, number> } = {
    active: null,
    unread: new Map(),
  };

  // The menu handlers are retained once and shared by every menu build
  // (the initial one and each rebuildMenu() refresh), so menu actions
  // always route through the same deps.ipcSend bridge.
  const handlers: TrayMenuHandlers = {
    show: () => deps.ipcSend(TRAY_COMMAND_CHANNEL, { kind: 'show' }),
    selectProfile: (id: string) => deps.ipcSend(TRAY_COMMAND_CHANNEL, { kind: 'select-profile', id }),
    toggleCloseToTray: () => deps.ipcSend(TRAY_COMMAND_CHANNEL, { kind: 'toggle-close-to-tray' }),
    toggleSyncAlerts: () => deps.ipcSend(TRAY_COMMAND_CHANNEL, { kind: 'toggle-sync-alerts' }),
    quit: () => {
      // The host-loop receiver owns app.quit() since step 5: this
      // handler only posts the intent; main.ts logs, notifies the main
      // window and quits (before-quit closes the tray).
      deps.ipcSend(TRAY_COMMAND_CHANNEL, { kind: 'quit' });
    },
  };
  // Mutable: rebuildMenu() assigns a fresh Menu over the current profile
  // list and preference (the same handlers); the tray itself is never
  // recreated.
  let menu = Menu.buildFromTemplate(
    buildTrayMenu(deps.getProfiles(), handlers, deps.getCloseToTray(), deps.getSyncAlerts()),
  );
  wireTrayEvents(tray, () => menu, process.platform);
  // Plain left-click restores+focuses the main window (the Show Phi intent).
  tray.on('click', () => handlers.show());

  const rebuildMenu = (): void => {
    menu = Menu.buildFromTemplate(
      buildTrayMenu(deps.getProfiles(), handlers, deps.getCloseToTray(), deps.getSyncAlerts()),
    );
  };

  const refreshTooltip = (): void => {
    const active = state.active;
    if (!active) {
      tray.setToolTip('Phi');
      return;
    }
    tray.setToolTip(
      buildTooltip({
        name: active.name,
        origin: active.origin,
        unread: state.unread.get(active.id),
      }),
    );
  };

  return {
    setActiveProfile(p: TrayProfile): void {
      state.active = p;
      refreshTooltip();
    },
    setUnread(profileId: string, n: number): void {
      state.unread.set(profileId, Math.max(0, n));
      if (state.active && state.active.id === profileId) refreshTooltip();
    },
    rebuildMenu,
    close(): void {
      tray.destroy();
    },
  };
}
